config/routes.rb
Rails.application.routes.draw do
  resources :doctors, :patients, :medications
  root to: "doctors#index"
  get "patients/create_patient/:id",to: 'patients#create_patient',as: 'patient_add'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	has_many :patients
end

app/models/medication.rb
class Medication < ActiveRecord::Base
	belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :medications
	belongs_to :doctor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	def index
		@doctor=Doctor.all
	end

	def show
		@doctor=Doctor.find(params[:id])
	end

	def new
		@doc_new=Doctor.new
	end

	def create
		@doc_new=Doctor.create(create_doc)
		if @doc_new.save
			redirect_to(doctors_path)
		end
	end

	def create_doc
		params.require(:doctor).permit(:name)
	end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	
	def show

	end

	def create_patient
		@pat=Patient.new
		@pat.doctor_id=params[:id]
		
	end

	def create
		@pat=Patient.create(new_patient)
		if @pat.save
			redirect_to(doctor_path(@pat.doctor_id))
		end
	end

	def new_patient
		params.require(:patient).permit(:name,:doctor_id)
	end

	def edit
		@pat_edit=Patient.find(params[:id])
	end

	def update

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_doc_create.html.erb
<%= form_for @doc_new do |f| %>
	<%= f.label :name %><br><br>
	<%= f.text_field :name %><br><br>
	<%= f.submit "create" %>
<% end %>

app/views/doctors/index.html.erb
<div class="container">
<div class="col-sm-2"><%= "list of doctors "%></div><br><br>

<div class="container">

<% @doctor.each do |doctor| %>
<ul>
	<div id="doc"><li><%= link_to doctor.name, doctor %></div></li>
</ul>
<% end %>

<%= link_to "create doctor", new_doctor_path %>
</div>
</div>

app/views/doctors/new.html.erb
<h3>create doctor</h3>

<%= render "doc_create" %>

app/views/doctors/show.html.erb
<% @doctor.patients.each do |patient| %>
	<ul><li><%=link_to patient.name,%><%= link_to "edit", edit_doctor_path %></li></ul>

<%end%>
<%= link_to "create patient", patient_add_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HospitalsBeta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/create_patient.html.erb
<%= form_for @pat do |f| %>
<br>
 <%= f.label :name, "patient_name"%>
 <%= f.text_field :name %>
 <%= f.hidden_field :doctor_id %>
 <%=f.submit "create" %>
<% end %>